import type { TemplateDesign } from '@/types/resume';

// Template design configurations for all 40+ templates
export const templateDesigns: Record<string, TemplateDesign> = {
  // Tech Templates
  'tech-modern': {
    fontFamily: 'inter',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'blue',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'badges',
      projects: 'cards',
      certifications: 'simple',
      header: 'photo-left',
      summary: 'paragraph',
    },
  },
  'tech-minimal': {
    fontFamily: 'roboto',
    fontSize: 'small',
    sectionSpacing: 'compact',
    colorScheme: 'neutral',
    headerStyle: 'minimal',
    sectionFormats: {
      workExperience: 'compact',
      education: 'minimal',
      skills: 'columns',
      projects: 'list',
      certifications: 'simple',
      header: 'left-aligned',
      summary: 'paragraph',
    },
  },
  'tech-creative': {
    fontFamily: 'playfair',
    fontSize: 'medium',
    sectionSpacing: 'spacious',
    colorScheme: 'purple',
    headerStyle: 'elegant',
    sectionFormats: {
      workExperience: 'creative',
      education: 'detailed',
      skills: 'cloud',
      projects: 'showcase',
      certifications: 'badges',
      header: 'photo-left',
      summary: 'highlight-box',
    },
  },
  'tech-professional': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'neutral',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'tech-ats': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'compact',
    colorScheme: 'neutral',
    headerStyle: 'minimal',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'columns',
      projects: 'list',
      certifications: 'simple',
      header: 'left-aligned',
      summary: 'paragraph',
    },
  },

  // Business Templates
  'business-executive': {
    fontFamily: 'merriweather',
    fontSize: 'large',
    sectionSpacing: 'spacious',
    colorScheme: 'neutral',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'executive',
      education: 'standard',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'highlight-box',
    },
  },
  'business-corporate': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'blue',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'cards',
      certifications: 'simple',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'business-consulting': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'green',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'two-column',
      summary: 'paragraph',
    },
  },
  'business-finance': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'neutral',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'detailed',
      skills: 'categorized',
      projects: 'list',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'business-startup': {
    fontFamily: 'inter',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'purple',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'modern',
      education: 'standard',
      skills: 'badges',
      projects: 'showcase',
      certifications: 'badges',
      header: 'photo-left',
      summary: 'highlight-box',
    },
  },
  'business-manager': {
    fontFamily: 'inter',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'orange',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'cards',
      certifications: 'simple',
      header: 'two-column',
      summary: 'paragraph',
    },
  },

  // Medical Templates
  'medical-clinical': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'blue',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'academic',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'medical-surgeon': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'blue',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'academic',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'medical-nurse': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'purple',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'list',
      certifications: 'detailed',
      header: 'photo-left',
      summary: 'paragraph',
    },
  },
  'medical-specialist': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'green',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'academic',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'medical-resident': {
    fontFamily: 'inter',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'blue',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'academic',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'medical-researcher': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'neutral',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'academic',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },

  // Legal Templates
  'legal-corporate': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'neutral',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'executive',
      education: 'academic',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'legal-litigation': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'blue',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'academic',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'legal-prosecutor': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'blue',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'academic',
      skills: 'categorized',
      projects: 'list',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'legal-paralegal': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'orange',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'list',
      certifications: 'detailed',
      header: 'two-column',
      summary: 'paragraph',
    },
  },
  'legal-associate': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'neutral',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'academic',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'legal-partner': {
    fontFamily: 'playfair',
    fontSize: 'large',
    sectionSpacing: 'spacious',
    colorScheme: 'neutral',
    headerStyle: 'elegant',
    sectionFormats: {
      workExperience: 'executive',
      education: 'academic',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'highlight-box',
    },
  },

  // Finance Templates
  'finance-analyst': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'neutral',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'detailed',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'finance-banker': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'blue',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'executive',
      education: 'detailed',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'finance-accountant': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'green',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'detailed',
      skills: 'categorized',
      projects: 'list',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'finance-advisor': {
    fontFamily: 'inter',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'blue',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'cards',
      certifications: 'detailed',
      header: 'photo-left',
      summary: 'paragraph',
    },
  },
  'finance-trader': {
    fontFamily: 'inter',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'orange',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'list',
      certifications: 'simple',
      header: 'two-column',
      summary: 'paragraph',
    },
  },
  'finance-auditor': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'neutral',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'detailed',
      skills: 'categorized',
      projects: 'list',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },

  // Marketing Templates
  'marketing-digital': {
    fontFamily: 'inter',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'purple',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'modern',
      education: 'standard',
      skills: 'badges',
      projects: 'showcase',
      certifications: 'badges',
      header: 'photo-left',
      summary: 'highlight-box',
    },
  },
  'marketing-content': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'green',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'showcase',
      certifications: 'simple',
      header: 'two-column',
      summary: 'paragraph',
    },
  },
  'marketing-brand': {
    fontFamily: 'playfair',
    fontSize: 'medium',
    sectionSpacing: 'spacious',
    colorScheme: 'purple',
    headerStyle: 'elegant',
    sectionFormats: {
      workExperience: 'creative',
      education: 'standard',
      skills: 'cloud',
      projects: 'showcase',
      certifications: 'badges',
      header: 'photo-left',
      summary: 'highlight-box',
    },
  },
  'marketing-social': {
    fontFamily: 'inter',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'purple',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'modern',
      education: 'standard',
      skills: 'badges',
      projects: 'cards',
      certifications: 'badges',
      header: 'photo-left',
      summary: 'paragraph',
    },
  },
  'marketing-growth': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'green',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'showcase',
      certifications: 'simple',
      header: 'two-column',
      summary: 'paragraph',
    },
  },
  'marketing-manager': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'orange',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'executive',
      education: 'standard',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },

  // Education Templates
  'education-teacher': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'blue',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'detailed',
      skills: 'categorized',
      projects: 'list',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'education-professor': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'neutral',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'academic',
      skills: 'categorized',
      projects: 'detailed',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'education-admin': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'purple',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'detailed',
      skills: 'categorized',
      projects: 'list',
      certifications: 'detailed',
      header: 'centered',
      summary: 'paragraph',
    },
  },
  'education-counselor': {
    fontFamily: 'roboto',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'green',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'detailed',
      skills: 'categorized',
      projects: 'list',
      certifications: 'detailed',
      header: 'photo-left',
      summary: 'paragraph',
    },
  },
  'education-special': {
    fontFamily: 'inter',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'purple',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'detailed',
      skills: 'categorized',
      projects: 'cards',
      certifications: 'detailed',
      header: 'photo-left',
      summary: 'paragraph',
    },
  },
  'education-coach': {
    fontFamily: 'merriweather',
    fontSize: 'medium',
    sectionSpacing: 'normal',
    colorScheme: 'orange',
    headerStyle: 'bold',
    sectionFormats: {
      workExperience: 'detailed',
      education: 'standard',
      skills: 'categorized',
      projects: 'cards',
      certifications: 'detailed',
      header: 'two-column',
      summary: 'paragraph',
    },
  },
};

export function getTemplateDesign(templateId: string): TemplateDesign | null {
  return templateDesigns[templateId] || null;
}
